version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: plush
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:a@postgres:5432/plush
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 16M
    ports:
      - "8080:8080"

volumes:
  postgres_data:
